[package]
name = "kemri_toy"
version = "0.1.0"
edition = "2024"
rust-version = "1.85.0"

[dependencies]
cms = { version = "0.3.0-pre.0", features = ["builder"] }
const-oid = { version = "0.10.1", default-features = false, features = ["db"] }
der = { version="0.8.0-rc.4", features = ["alloc", "derive", "flagset", "oid"] }
spki = { version = "0.8.0-rc.2", default-features = false, features = ["alloc"] }
x509-cert = { version = "0.3.0-rc.0", default-features = false, features = ["hazmat", "builder"] }
pqckeys = { git = "https://github.com/carl-wallace/pqckeys", branch = "kemri", features = ["pem"] }

aes = { version = "=0.9.0-rc.0" }
aes-gcm = "0.11.0-rc.0"
aes-kw ="0.3.0-rc.0"
cbc = { version = "0.2.0-rc.0" }
cipher = { version = "0.5.0-rc.0", features = ["alloc", "block-padding", "rand_core"] }
hkdf = "0.13.0-rc.0"
ml-dsa = "0.1.0-pre.2"
ml-kem = { version = "0.3.0-pre", features=["deterministic"] }
slh-dsa = "0.2.0-pre"
rsa = { version = "0.10.0-rc.0", features = ["sha2"] }
sha2 = "0.11.0-rc.0"
signature = { version = "3.0.0-rc.1", features = ["digest", "alloc"]}
tari-tiny-keccak = { version = "2.0.2", features = ["kmac"] }

clap = {version = "4.4.40", features = ["std", "derive"] }
log = "0.4.27"
log4rs = "1.3.0"
rand_core = { version = "0.9.3", features = ["std"] }
rand = "0.9.1"
serde = { version = "1.0.219", default-features = false, features = ["derive"] }
subtle-encoding = {version = "0.5.1", default-features = false, features = ["hex", "alloc"]}
zerocopy = "0.8.26"

[patch.crates-io]
aes-gcm       = { git="https://github.com/RustCrypto/AEADs.git" }

aes           = { git = "https://github.com/RustCrypto/block-ciphers.git" }

cbc           = { git = "https://github.com/RustCrypto/block-modes.git" }
ctr           = { git = "https://github.com/RustCrypto/block-modes.git" }

crypto-bigint = { git = "https://github.com/RustCrypto/crypto-bigint.git" }

cms           = { git = "https://github.com/RustCrypto/formats.git" }
der           = { git = "https://github.com/RustCrypto/formats.git" }
der_derive    = { git = "https://github.com/RustCrypto/formats.git" }
pkcs1         = { git = "https://github.com/RustCrypto/formats.git" }
pkcs8         = { git = "https://github.com/RustCrypto/formats.git" }
spki          = { git = "https://github.com/RustCrypto/formats.git" }
x509-cert     = { git = "https://github.com/RustCrypto/formats.git" }

sha2          = { git = "https://github.com/RustCrypto/hashes.git" }

ml-kem        = { git = "https://github.com/RustCrypto/KEMs.git"}

aes-kw        = { git = "https://github.com/RustCrypto/key-wraps.git" }

rsa           = { git = "https://github.com/RustCrypto/RSA.git" }

ml-dsa        = { git = "https://github.com/RustCrypto/signatures" }
slh-dsa       = { git = "https://github.com/RustCrypto/signatures" }

aead          = { git = "https://github.com/RustCrypto/traits.git" }
cipher        = { git = "https://github.com/RustCrypto/traits.git" }
crypto-common = { git = "https://github.com/RustCrypto/traits.git" }
digest        = { git = "https://github.com/RustCrypto/traits.git" }
kem           = { git = "https://github.com/RustCrypto/traits.git" }
signature     = { git = "https://github.com/RustCrypto/traits.git" }
